/* STYLE REMINDER — Central company journal: official updates first, readable field notes second, all in one list with simple in-page expansion. */
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, ChevronDown, Instagram, Linkedin, MapPin } from "lucide-react";
import { Link } from "wouter";

const LOGO = "/manus-storage/raphael-logo_4f5b0bc1.png";

type Post = { type: "Official update" | "Field note"; tag: string; title: string; intro: string; body: string };
const posts: Post[] = [
  { type: "Official update", tag: "Company milestone", title: "Vayal Vimaani application demo launch", intro: "A public milestone for a farmer-first drone service from Raphael Drones.", body: "Raphael Drones shared the first demo launch of the Vayal Vimaani application, connecting agricultural drone work with practical support for farmers. This record is based on the company’s public milestone post." },
  { type: "Official update", tag: "MoU / collaboration", title: "RVCE Sivakasi seminar and collaboration", intro: "A shared space for drone technology, GIS, skill development, and innovation.", body: "The RVCE Sivakasi seminar and collaboration milestone brought together ideas around drone technology, precision agriculture, skill development, and innovation. Add the official agreement date, photographs, and document link here when approved for publication." },
  { type: "Official update", tag: "Training record", title: "Building practical pilot capability", intro: "A place to record future training batches, seminars, workshops, and field-learning moments.", body: "Use this central journal to publish confirmed training dates, learning outcomes, partner institutions, and approved photographs as they happen. Only verified records should be added to the public archive." },
  { type: "Field note", tag: "Precision agriculture", title: "What drone spraying changes for a working farm", intro: "A clearer look at how aerial application can support timing, coverage, and practical field decisions.", body: "Drone-based spraying is not about replacing farming knowledge. It is about helping a team apply the right work across a field with less walking, measured coverage, and a clearer view of the operation. The right approach depends on crop, field condition, approved inputs, weather, and local requirements." },
  { type: "Field note", tag: "GIS + LiDAR", title: "From aerial capture to a map you can use", intro: "Why useful geospatial work begins with the decision—not the equipment.", body: "Aerial imagery, GIS, and LiDAR become valuable when they help someone decide what to inspect, measure, plan, or improve next. A good workflow starts with the question, chooses the right capture method, and turns the result into information that a field team or decision-maker can understand." },
  { type: "Field note", tag: "Pilot learning", title: "From first flight to field-ready", intro: "A practical way to think about drone pilot training and responsible operations.", body: "Good pilot learning combines aircraft basics, safety, operating discipline, mission planning, and practical confidence. For formal remote pilot licensing, training and assessment follow the requirements of the relevant aviation authority and the applicable RPTO pathway." },
  { type: "Field note", tag: "Vayal Vimaani", title: "Bringing precision spraying closer to farmers", intro: "How Vayal Vimaani connects agricultural drone work with a simple farmer-first service model.", body: "Vayal Vimaani is built around a straightforward idea: make modern crop-spraying support easier to access. The service brings trained operators, agricultural drone systems, and practical field coordination together so farmers can ask the right questions before work begins." },
];

export default function Journal() {
  const [open, setOpen] = useState<string | null>(null);
  const [filter, setFilter] = useState<"All" | Post["type"]>("All");
  const visible = filter === "All" ? posts : posts.filter((post) => post.type === filter);
  useEffect(() => { document.title = "Journal — Raphael Drones"; }, []);

  return (
    <div className="archive-page journal-page">
      <header className="archive-header"><div className="archive-topline"><span>Raphael Drones & GIS Services</span><span>Ideas from the field</span></div><div className="site-width archive-nav"><Link href="/" className="archive-brand"><img src={LOGO} alt="Raphael Drones" /></Link><nav><Link href="/">Home</Link><Link href="/gallery">Gallery</Link><Link href="/journal" className="active">Journal</Link></nav><a href="https://www.linkedin.com/company/raphael-drones-and-gis-services" target="_blank" rel="noreferrer" className="archive-social"><Linkedin size={15} /> LinkedIn <ArrowUpRight size={13} /></a></div></header>
      <main><section className="archive-hero journal-hero"><div className="site-width archive-hero-grid"><div><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to Raphael Drones</Link><div className="eyebrow copper-line">Journal / company index</div><h1>Everything<br /><span>in view.</span></h1></div><div className="archive-intro"><p>Official company updates, MoUs, milestones, training records, and practical field notes in one readable place.</p><div className="archive-location"><MapPin size={15} /> Written from Tamil Nadu</div></div></div></section><section className="journal-list-section"><div className="site-width"><div className="journal-toolbar"><div><span className="eyebrow copper-line">Company journal</span><strong>{visible.length} visible posts</strong></div><div className="filter-wrap"><button className={filter === "All" ? "filter-button active" : "filter-button"} onClick={() => setFilter("All")}>All</button><button className={filter === "Official update" ? "filter-button active" : "filter-button"} onClick={() => setFilter("Official update")}>Official updates</button><button className={filter === "Field note" ? "filter-button active" : "filter-button"} onClick={() => setFilter("Field note")}>Field notes</button></div></div><div className="journal-list">{visible.map((post, index) => <article className={open === post.title ? "journal-card open" : "journal-card"} key={post.title}><div className="journal-number">{String(index + 1).padStart(2, "0")}</div><div className="journal-card-main"><div className={post.type === "Official update" ? "journal-tag official" : "journal-tag"}>{post.type} · {post.tag}</div><h2>{post.title}</h2><p>{post.intro}</p>{open === post.title && <div className="journal-body"><p>{post.body}</p><span>Raphael Drones & GIS Services</span></div>}</div><button aria-expanded={open === post.title} aria-label={`Read ${post.title}`} onClick={() => setOpen(open === post.title ? null : post.title)}><ChevronDown size={19} /></button></article>)}</div><div className="journal-footer-note"><span>Use this central index for every approved company update, event, training record, and field note.</span><a href="https://www.linkedin.com/company/raphael-drones-and-gis-services" target="_blank" rel="noreferrer">Follow official posts on LinkedIn <ArrowUpRight size={14} /></a></div></div></section></main>
      <footer className="archive-footer"><div className="site-width archive-footer-inner"><div><img src={LOGO} alt="Raphael Drones" /><p>Practical aerial technology for fields, teams, and what comes next.</p></div><div className="archive-footer-links"><Link href="/gallery">View the Gallery <ArrowUpRight size={14} /></Link><a href="https://www.linkedin.com/company/raphael-drones-and-gis-services" target="_blank" rel="noreferrer"><Linkedin size={14} /> LinkedIn</a><a href="https://www.instagram.com/raphael_drones_gis_services/" target="_blank" rel="noreferrer"><Instagram size={14} /> Instagram</a></div></div></footer>
    </div>
  );
}
